apiVersion: apps/v1
kind: Deployment
metadata:
  name: test6637
  labels:
    app: test6637
  namespace: namespace-workflow-1690441262371
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test6637
  template:
    metadata:
      labels:
        app: test6637
    spec:
      containers:
        - name: test6637
          image: aksregistry6637.azurecr.io/image-workflow-1690441262371:latest
          ports:
            - containerPort: 8000