apiVersion: apps/v1
kind: Deployment
metadata:
  name: CnD
  labels:
    app: CnD
  namespace: contndeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CnD
  template:
    metadata:
      labels:
        app: CnD
    spec:
      containers:
        - name: CnD
          image: testreg66378.azurecr.io/cndimage:latest
          ports:
            - containerPort: 8000