apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1689761443388
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000