apiVersion: v1
kind: Service
metadata:
  name: testworkflow
  namespace: namespace-workflow-1689902343106
spec:
  type: LoadBalancer
  selector:
    app: testworkflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000